"""Database alter table users

Revision ID: be50a5e05a07
Revises: 54e570b71f3a
Create Date: 2024-05-15 14:26:28.278265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be50a5e05a07'
down_revision = '54e570b71f3a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'search_interval',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'search_interval',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###